import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { FlatList } from '../components/FlatList';
import type { FlatType } from '../lib/types/entities';
import { useStore } from '../lib/store/useStoreHook';
import useSWR from 'swr';

type HomePageProps = {
  preloadedFlatList: FlatType[];
};

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage<HomePageProps> = () => {
  const { data, error } = useSWR('/api/getFlats', fetcher);
  const flats = useStore(state => state.flats);
  const setFlats = useStore(state => state.setFlats);

  if (!flats || !flats.length) {
    setFlats(data);
  }

  if (!flats || !flats.length) {
    return <div>No flats</div>;
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Flat Power Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <FlatList flats={flats} />
      </body>
    </div>
  );
};

export default Home;
