import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { flatMocks } from '../lib/mock/mock';
import { FlatList } from '../components/FlatList';
import type { FlatType } from '../lib/types/entities';

type HomePageProps = {
  preloadedFlatList: FlatType[];
};

const Home: NextPage<HomePageProps> = ({ preloadedFlatList }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Flat Power Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className="flats-container">
          <FlatList flats={preloadedFlatList} />
        </div>
      </body>
    </div>
  );
};
Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/flats');
  const json = await res.json();
  console.log(json, 'JSON');
  return { preloadedFlatList: json };
};
export default Home;
